#spring.datasource.url=jdbc:postgresql://localhost:5432/jus_db
#spring.datasource.username=postgres
#spring.datasource.password=root

spring.datasource.url=jdbc:mysql://localhost:3306/local_wakati
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true



spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


sms.api-key= example
bulk.sms.api-url=https://bulksmsapi.ctvas.km/api/V2

#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true