package com.wakati.enums;

public enum CollectionRequestStatus {
    RECEIVER_RAISED,
    SUPER_DEALER_NOTIFIED,
    DEALER_NOTIFIED,
    AMOUNT_DECLARED,
    COLLECTED_DEALER_TO_SUPER_DEALER,
    COLLECTED_SUPER_DEALER_TO_RECEIVER,
    COMPLETED,
    PARTNER_AGENT_RAISED,
    COLLECTED_SUPER_DEALER_TO_PARTNER_AGENT
}
