package com.wakati.enums;

public enum DocumentType {
    ID,
    PHOTO,
    REQUEST_LETTER,
    NATIONAL_IDENTITY_CARD,
    PORTRAIT_PHOTO,
    COMMERICIAL_REGISTRATION_DOCUMENT,
    PROOF_OF_ADDRESS,
    POINT_OF_SALE_PHOTO,
    POINT_OF_SALE_LOCATION_MAP,
    SIGNED_CONTRACT,
    TAX_DOCUMENT,
    TRADE_REGISTER,
    MANAGER_PHOTO,
    MANAGER_ARTICLE_DOCUMENT,
    MANAGER_RC_DOCUMENT
}