package com.wakati.enums;

public enum OtpPurpose {
    REGISTER, LOGIN, PASSWORD_RESET, PIN_RESET, TRANSACTION_CONFIRM,
    COLLECT_CASH_DEALER, COLLECT_CASH_SUPER_DEALER,
    PAY_CASH_RECEIVER_TO_SD, PAY_CASH_SD_TO_DEALER,
    COLLECT_CASH_SUPER_DEALER_TO_PARTNER_AGENT,
    COLLECT_CASH_PARTNER_AGENT_TO_RECEIVER,
    PAY_CASH_RECEIVER_TO_PARTNER_AGENT,
    PAY_CASH_PARTNER_AGENT_TO_SD
}
